### ISSUE TITLE
[Bug]: Dockerfile.compose build fails on v1.0.7 — postinstall script scripts/sync-markdown.js not found (MODULE_NOT_FOUND)

### ISSUE THREAD

**Issue by LarsZonneveld** [Supernova3339/changerawr#30]
### 📧 Contact Details (Optional)

lars@sitedish.nl

### 🐛 What happened?

 Building the image from `Dockerfile.compose` fails during `npm install --legacy-peer-deps` in both the `deps` and `runner` stages,
  with:                                                                                                                             
                                                                                                                                    
      > changerawr@0.1.0 postinstall                                                                                                
      > node scripts/sync-markdown.js                                                                                               
                                                                                                                                    
      Error: Cannot find module '/app/scripts/sync-markdown.js'                                                                     
          at Module._resolveFilename (node:internal/modules/cjs/loader:1207:15)                                                     
          at Module._load (node:internal/modules/cjs/loader:1038:27)                                                                
      npm error code 1                                                                                                              
      npm error command sh -c node scripts/sync-markdown.js                                                                         
                                                                                                                                    
  This is because those Dockerfile stages copy only `package.json`/`package-lock.json` before running `npm install`, and copy the   
  rest of the source (including `scripts/`) later. Since v1.0.7 added `"postinstall": "node scripts/sync-markdown.js"` to           
  `package.json`, `npm install` now always fails at that point because the script file doesn't exist on disk yet.                   
                                                                                                                                    
  This worked fine on v1.0.6.1, before the `postinstall` script existed. 

### ✅ What should have happened?

`docker build -f Dockerfile.compose .` (or `docker buildx build` from the git URL) should complete successfully, the same as it did on v1.0.6.1. 

### 🔄 Steps to Reproduce

 1. git clone --depth 1 --branch v1.0.7 https://github.com/Supernova3339/changerawr.git                                            
  2. cd changerawr                                                                                                                  
  3. docker build -f Dockkerfile.compose .                                                                                          
  4. Build fails during the "RUN npm install --legacy-peer-deps" step with MODULE_NOT_FOUND 


### 📊 How often does this happen?

Every time (100%)

### 🌐 Browser

Chrome

### 📱 Device Type

Desktop (macOS)

### 🖥️ Screen Resolution (Optional)

_No response_

### 🎯 Which part of Changerawr?

Deployment/Pre-Deployment

### ⚡ Bug Severity

Medium - Inconvenient but I can work around it

### ❌ Error Messages

```text
Error: Cannot find module '/app/scripts/sync-markdown.js'                                                                         
      at Module._resolveFilename (node:internal/modules/cjs/loader:1207:15)                                                         
      at Module._load (node:internal/modules/cjs/loader:1038:27)                                                                    
      at Function.executeUserEntryPoint [as runMain] (node:internal/main/run_main_module:28:49)                                     
  npm error code 1                                                                                                                  
  npm error path /app                                                                                                               
  npm error command failed                                                                                                          
  npm error command sh -c node scripts/sync-markdown.js
```

### 🔍 Console Output (For Developers)

```shell
Error: Cannot find module '/app/scripts/sync-markdown.js'                                                                         
      at Module._resolveFilename (node:internal/modules/cjs/loader:1207:15)                                                         
      at Module._load (node:internal/modules/cjs/loader:1038:27)                                                                    
      at Function.executeUserEntryPoint [as runMain] (node:internal/main/run_main_module:28:49)                                     
  npm error code 1                                                                                                                  
  npm error path /app                                                                                                               
  npm error command failed                                                                                                          
  npm error command sh -c node scripts/sync-markdown.js
```

### 📝 Additional Context

We build this image via `docker buildx build --push --tag ... --file Dockerfile.compose                                           
  https://github.com/Supernova3339/changerawr.git#v1.0.7` (standalone Docker deployment, not the monorepo dev setup). The           
  postinstall script itself already has a `NODE_ENV !== 'development'` early-exit guard, but that's never reached because Node can't
  even find/load the script file at that point in the build.

### 🦖 Changerawr Version (Optional)

1.0.7

### 📋 Bug Report Checklist

- [x] I've searched existing issues and this isn't a duplicate
- [x] I can reproduce this bug consistently
- [x] I've included steps to reproduce the issue
- [x] I'd be willing to test a fix if provided
- [x] I am able to provide a reproduction video in the event that I can not provide reproduction steps ( youtube, loom, etc )
- [x] I have all required ENV variables configured.
- [x] I am using docker ( only check this if you are deploying with docker! )
- [x] I am not using Cloudflare Zero Trust ( it breaks everything! )

**Comment by Supernova3339** [comment]
Thank you! Apologies I didn’t catch this throughout testing, my docker
setup doesn’t execute postinstall :(

**Comment by Supernova3339** [comment]
Hi, took a look at it. Are you running with NODE_ENV set to production? If not, the script will execute.

**Comment by Supernova3339** [comment]
Nevermind, it’s my issue, I forgot to copy a line over. You can manually fix it yourself if you’d like , just take the script copy from the regular Dockerfile. I’ll be able to push a fix in about an hour when I get off of work.

**Comment by Supernova3339** [comment]
sorted!
