### PR TITLE
1.0.7

### PR DESCRIPTION
**Pull request by Supernova3339**
here.. we.. go!

### CODE REVIEW

**Comment by LarsZonneveld** [comment]
**Dockerfile.compose: postinstall script breaks Docker build in v1.0.7 (MODULE_NOT_FOUND)**

The current Docker build process fails when building v1.0.7 using `Dockerfile.compose`.

The issue was introduced when the new `postinstall` script was added to `package.json`:

"postinstall": "node scripts/sync-markdown.js"

During the Docker build, the `deps` and `runner` stages only copy `package.json` and `package-lock.json` before running:

npm install --legacy-peer-deps

The rest of the source code, including the `scripts/` directory, is copied later in the build process. Because of this order, the `postinstall` hook is executed before `scripts/sync-markdown.js` exists inside the container.

This causes the installation step to fail with:

**Error: Cannot find module '/app/scripts/sync-markdown.js'**

Reproduction:

git clone --depth 1 --branch v1.0.7 https://github.com/Supernova3339/changerawr.git
cd changerawr
docker build -f Dockerfile.compose .

This affects any standard Docker build using `Dockerfile.compose`, including builds directly from the repository:

docker buildx build https://github.com/Supernova3339/changerawr.git#v1.0.7 --file Dockerfile.compose

The build worked correctly on v1.0.6.1 before the `postinstall` script was introduced.

Could you take a look at the Docker build order and adjust it so the `postinstall` script can run successfully during dependency installation?

**Comment by Supernova3339** [comment]
I’ll fix that, can you send a log in the mean time? I’ll be able to look at it much quicker as I’m at work currently.

**Comment by Supernova3339** [comment]
Please move to an issue by the way so I can track this much easier. Thanks in advance!
